### ISSUE TITLE
[bug] Error when parsing hashes in sectools/windows/crypto.py

### ISSUE THREAD

**Issue by LightxR** [p0dalirius/sectools#9]
I encounter some error while playing with ldapconsole (which uses parse_lm_nt_hashes function from sectools)

<img width="734" alt="crypto" src="https://github.com/user-attachments/assets/f2e921f2-3bef-4e7c-9c61-a08512ee1437">

It looks like the function can't handle the hash when provided in `lm:nt` format

Looking at the code, we can simply it a little bit and add an else condition : 

```python
def parse_lm_nt_hashes(lm_nt_hashes_string):
    lm_hash_value, nt_hash_value = "", ""
    if lm_nt_hashes_string is not None:
        matched = re.match("([0-9a-f]{32})?(:)?([0-9a-f]{32})?", lm_nt_hashes_string.strip().lower())
        m_lm_hash, _, m_nt_hash = matched.groups()
        if m_lm_hash is None and m_nt_hash is not None:
            lm_hash_value = "aad3b435b51404eeaad3b435b51404ee"
            nt_hash_value = m_nt_hash
        elif m_lm_hash is not None and m_nt_hash is None:
            lm_hash_value = m_lm_hash
            nt_hash_value = nt_hash("")
        else:
            lm_hash_value = m_lm_hash
            nt_hash_value = m_nt_hash
    return lm_hash_value, nt_hash_value
```

Now, with this modification, it works 👍 

<img width="734" alt="crypto2" src="https://github.com/user-attachments/assets/65557630-2e5d-46db-92cd-302cc7e543c1">

Thanks for your work and awesome tools :)

**Comment by p0dalirius** [comment]
Thank you !
